# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30797c270ddff45f9c715c70623ceb4ae43ea38fdf844be21d4d622b519d8b88048470718d432e716193c597b80f1bd9ea8bf2ca4bb349edea30ee0a33e02f58

test:
  secret_key_base: f1b24f89280f88f59c30fee56bf6bf803cd8563bf06e876340e4493d510f256208d6d8dfb3493e1c08d695cec7ca1e386428ae8befc4c77ec1601fa2d8cde1e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
